eureka:
  client:
    register-with-eureka: false

server:
  port: 8222

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: student
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/students/**
          filters:
            - AuthenticationFilter
        - id: school
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/schools/**
          filters:
            - AuthenticationFilter
        - id: auth-server
          uri: http://localhost:8060
          predicates:
            - Path=/auth/**

jwt:
  access:
    secret:
      key: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437

management:
  tracing:
    sampling:
      probability: 1.0